#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WorkoutWotch.Services.Android.Resource", IsApplication=false)]

namespace WorkoutWotch.Services.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public static int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public static int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public static int common_action_bar_splitter = 2130968585;
			
			// aapt resource value: 0x7f040000
			public static int common_signin_btn_dark_text_default = 2130968576;
			
			// aapt resource value: 0x7f040002
			public static int common_signin_btn_dark_text_disabled = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int common_signin_btn_dark_text_focused = 2130968579;
			
			// aapt resource value: 0x7f040001
			public static int common_signin_btn_dark_text_pressed = 2130968577;
			
			// aapt resource value: 0x7f040008
			public static int common_signin_btn_default_background = 2130968584;
			
			// aapt resource value: 0x7f040004
			public static int common_signin_btn_light_text_default = 2130968580;
			
			// aapt resource value: 0x7f040006
			public static int common_signin_btn_light_text_disabled = 2130968582;
			
			// aapt resource value: 0x7f040007
			public static int common_signin_btn_light_text_focused = 2130968583;
			
			// aapt resource value: 0x7f040005
			public static int common_signin_btn_light_text_pressed = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public static int common_signin_btn_text_dark = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public static int common_signin_btn_text_light = 2130968587;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int common_ic_googleplayservices = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int common_signin_btn_text_pressed_light = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public static int adjust_height = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int adjust_width = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int none = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public static int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030023
			public static int ApplicationName = 2130903075;
			
			// aapt resource value: 0x7f030022
			public static int Hello = 2130903074;
			
			// aapt resource value: 0x7f030001
			public static int auth_google_play_services_client_facebook_display_name = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int auth_google_play_services_client_google_display_name = 2130903040;
			
			// aapt resource value: 0x7f030004
			public static int common_android_wear_notification_needs_update_text = 2130903044;
			
			// aapt resource value: 0x7f030011
			public static int common_android_wear_update_text = 2130903057;
			
			// aapt resource value: 0x7f03000f
			public static int common_android_wear_update_title = 2130903055;
			
			// aapt resource value: 0x7f03001d
			public static int common_google_play_services_api_unavailable_text = 2130903069;
			
			// aapt resource value: 0x7f03000d
			public static int common_google_play_services_enable_button = 2130903053;
			
			// aapt resource value: 0x7f03000c
			public static int common_google_play_services_enable_text = 2130903052;
			
			// aapt resource value: 0x7f03000b
			public static int common_google_play_services_enable_title = 2130903051;
			
			// aapt resource value: 0x7f030006
			public static int common_google_play_services_error_notification_requested_by_msg = 2130903046;
			
			// aapt resource value: 0x7f03000a
			public static int common_google_play_services_install_button = 2130903050;
			
			// aapt resource value: 0x7f030008
			public static int common_google_play_services_install_text_phone = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int common_google_play_services_install_text_tablet = 2130903049;
			
			// aapt resource value: 0x7f030007
			public static int common_google_play_services_install_title = 2130903047;
			
			// aapt resource value: 0x7f030017
			public static int common_google_play_services_invalid_account_text = 2130903063;
			
			// aapt resource value: 0x7f030016
			public static int common_google_play_services_invalid_account_title = 2130903062;
			
			// aapt resource value: 0x7f030005
			public static int common_google_play_services_needs_enabling_title = 2130903045;
			
			// aapt resource value: 0x7f030015
			public static int common_google_play_services_network_error_text = 2130903061;
			
			// aapt resource value: 0x7f030014
			public static int common_google_play_services_network_error_title = 2130903060;
			
			// aapt resource value: 0x7f030003
			public static int common_google_play_services_notification_needs_update_title = 2130903043;
			
			// aapt resource value: 0x7f030002
			public static int common_google_play_services_notification_ticker = 2130903042;
			
			// aapt resource value: 0x7f03001f
			public static int common_google_play_services_sign_in_failed_text = 2130903071;
			
			// aapt resource value: 0x7f03001e
			public static int common_google_play_services_sign_in_failed_title = 2130903070;
			
			// aapt resource value: 0x7f030018
			public static int common_google_play_services_unknown_issue = 2130903064;
			
			// aapt resource value: 0x7f03001a
			public static int common_google_play_services_unsupported_text = 2130903066;
			
			// aapt resource value: 0x7f030019
			public static int common_google_play_services_unsupported_title = 2130903065;
			
			// aapt resource value: 0x7f03001b
			public static int common_google_play_services_update_button = 2130903067;
			
			// aapt resource value: 0x7f030010
			public static int common_google_play_services_update_text = 2130903056;
			
			// aapt resource value: 0x7f03000e
			public static int common_google_play_services_update_title = 2130903054;
			
			// aapt resource value: 0x7f030013
			public static int common_google_play_services_updating_text = 2130903059;
			
			// aapt resource value: 0x7f030012
			public static int common_google_play_services_updating_title = 2130903058;
			
			// aapt resource value: 0x7f03001c
			public static int common_open_on_phone = 2130903068;
			
			// aapt resource value: 0x7f030020
			public static int common_signin_button_text = 2130903072;
			
			// aapt resource value: 0x7f030021
			public static int common_signin_button_text_long = 2130903073;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public static int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public static int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public static int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
